### ISSUE TITLE
Cannot start server

### ISSUE THREAD

**Issue by McKitten** [DakotaPride/Hibernal-Herbs#6]
fabric-server-mc.1.19.2-loader.0.14.16-launcher.0.11.2 and 14.17
versions 0.5.3 (modrinth) & 0.7a (cf)
both part of a pack I've been trying to get going for my peeps.

https://mclo.gs/DVg8tTB

As you can probably see this is 1 of 3 I've had issues with, but i don't know fabric well enough to know what else to try.
Perhaps you know what it's problem is?

**Comment by DakotaPride** [comment]
@McKitten As far as I can tell, I think the main issue may be caused by how I version the mod. In all fairness, how I've done it isn't a great idea and will be changed in the upcoming version. Though, I am somewhat confused by this. Are you trying to host 2 separate servers or just 1? (may be useful to provide the logs/crash reports for both just in case the issue persists throughout the versions. Though, I doubt that it does)

**Comment by DakotaPride** [comment]
I apologize for taking so long to reply, but I have been having some technical difficulties with my PC, so it may take a while to get to this issue. I will make sure to reply to you with the corresponding information as soon as possible! Thank you for your patience and understanding! (again, apologies)

**Comment by DakotaPride** [comment]
@McKitten Please try updating now (both Modrinth and Curseforge pages have been updated, so let me know if any further issues persist or occur! Sorry for the longish wait on notifying you on this as well!)
